version: '3.8'

services:
    api:
        container_name: zenvus-api-staging
        image: us-central1-docker.pkg.dev/zenvus-484311/zenvus-api/zenvus-api:staging
        ports:
            - "${APP_PORT}:8080"
    
        environment:
            ENVIRONMENT: staging
            ASPNETCORE_ENVIRONMENT: Staging
            ConnectionStrings__Default: ${DB_CONNECTION_STRING}
        dns:
            - 8.8.8.8
        networks:
            - api
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 256M

networks:
    api:
        name: applications_bridge
        external: true
