name: Deploy Backend - Cloud Run

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - "server/**"

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-staging
    env: 
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/zenvus-api:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify auth
      run: gcloud auth list

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet
      
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME
    
    - name: Push Docker Image
      run: docker push $IMAGE_NAME
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy zenvus-api \
          --image $IMAGE_NAME \
          --region us-central1 \
          --memorry 128Mi
          --min-instances 0
          --max-instances 1
          --platform managed \
          --port 80
          --allow-unauthenticated \
          --set-env-vars ConnectionStrings__Default=${{ secrets.DB_CONNECTION_STRING }}
