name: Deploy Backend - Cloud Run

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Build & Push Docker Image
      run: |
        gcloud builds submit server \
          --tag ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/zenvus-api/zenvus-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy zenvus-api \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/zenvus-api/zenvus-api \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars ConnectionStrings__Default=${{ secrets.DB_CONNECTION_STRING }}
